import { StyleSheet, Platform } from "react-native";

/* =========================================================
   COLORS
========================================================= */
export const colors = {
    bg: "#f5f8fc",
    card: "#ffffff",
    border: "#e5eaf1",
    border2: "#e2e8f0",
    text: "#172033",
    subtext: "#64748b",
    muted: "#94a3b8",
    blue: "#2563eb",
    blueDark: "#1d4ed8",
    blueBg: "#eff6ff",
    blueBorder: "#dbeafe",
    green: "#16a34a",
    greenBg: "#ecfdf5",
    greenText: "#059669",
    orange: "#c2410c",
    orangeBg: "#fff7ed",
    orangeBorder: "#fed7aa",
    red: "#dc2626",
    redBg: "#fff1f2",
    redBorder: "#fecdd3",
};


export const techniciandashboard = StyleSheet.create({
    /* ===================== SCREEN ===================== */
    screen: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    scrollContent: {
       padding:20
    },
    centerScreen: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.bg,
    },
    loadingTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: colors.text,
        marginBottom: 6,
    },
    loadingSub: {
        fontSize: 13,
        color: colors.muted,
    },
   header: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 18,
        padding: 18,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: "700",
        color: colors.text,
    },
    headerSub: {
        fontSize: 13,
        color: colors.subtext,
    },

    headerActions: {
        flexDirection: "row",
        gap: 8,
    },
    btnRefresh: {
        borderWidth: 1,
        borderColor: colors.blueBorder,
        backgroundColor: colors.blueBg,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    btnRefreshText: {
        color: colors.blue,
        fontWeight: "600",
        fontSize: 13,
    },
    btnLogout: {
        borderWidth: 1,
        borderColor: colors.redBorder,
        backgroundColor: colors.redBg,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    btnLogoutText: {
        color: colors.red,
        fontWeight: "600",
        fontSize: 13,
    },

    /* ===================== WELCOME ===================== */
    welcomeCard: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border2,
        borderRadius: 18,
        padding: 20,
        marginBottom: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    welcomeLabel: {
        color: colors.blue,
        fontSize: 11,
        fontWeight: "700",
        textTransform: "uppercase",
        marginBottom: 6,
    },
    welcomeName: {
        fontSize: 20,
        fontWeight: "700",
        color: colors.text,
        marginBottom: 4,
    },
    welcomeSub: {
        fontSize: 13,
        color: colors.subtext,
    },
    roleBadge: {
        backgroundColor: colors.blueBg,
        borderWidth: 1,
        borderColor: colors.blueBorder,
        borderRadius: 30,
        paddingVertical: 8,
        paddingHorizontal: 14,
    },
    roleBadgeText: {
        color: colors.blue,
        fontSize: 12,
        fontWeight: "700",
        textTransform: "capitalize",
    },

    /* ===================== SECTIONS ===================== */
    sectionTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: colors.text,
        marginBottom: 10,
        marginTop: 6,
    },
    infoGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
        marginBottom: 16,
    },
    infoCard: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 14,
        padding: 14,
        minWidth: "47%",
        flexGrow: 1,
    },



    safeArea: {
        backgroundColor: "#FFFFFF",
    },
    infoLabel: {
        color: "#8a96a8",
        fontSize: 10,
        fontWeight: "600",
        textTransform: "uppercase",
        marginBottom: 5,
    },
    infoValue: {
        color: "#263449",
        fontSize: 13,
        fontWeight: "700",
    },

    companyCard: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 14,
    },
    companyBlock: { minWidth: "45%" },
    companyLabel: {
        color: "#8a96a8",
        fontSize: 10,
        fontWeight: "600",
        textTransform: "uppercase",
        marginBottom: 5,
    },
    companyValueLg: { fontSize: 16, fontWeight: "700", color: colors.text },
    companyValue: { fontSize: 13, color: "#344054", fontWeight: "600" },
    tasksHeader: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    tasksHeaderTitle: { fontSize: 18, fontWeight: "700", color: colors.text },
    tasksHeaderSub: { fontSize: 12, color: "#8792a4", marginTop: 2 },
    countPill: {
        backgroundColor: colors.blueBg,
        borderWidth: 1,
        borderColor: colors.blueBorder,
        borderRadius: 25,
        paddingVertical: 6,
        paddingHorizontal: 12,
    },
    countPillText: { color: colors.blue, fontWeight: "700", fontSize: 12 },

    /* ===================== STATUS TABS ===================== */
    tabsRow: {
        flexDirection: "row",
        gap: 8,
        marginBottom: 14,
    },

    tabBtn: {
        paddingVertical: 9,
        paddingHorizontal: 12,
        borderRadius: 10,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border2,
    },
    tabBtnActive: {
        backgroundColor: colors.blue,
        borderColor: colors.blue,
    },
    tabBtnText: { fontSize: 12, fontWeight: "700", color: colors.subtext },
    tabBtnTextActive: { color: "#fff" },

    /* ===================== JOB CARD ===================== */
    jobCard: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border2,
        borderRadius: 14,
        padding: 15,
        marginBottom: 12,
    },
    jobCardUnassigned: {
        borderWidth: 2,
        borderColor: "#f59e0b",
        borderStyle: "dashed",
    },
    jobCardClosed: { opacity: 0.65 },
    badge: {
        alignSelf: "flex-start",
        borderRadius: 20,
        paddingVertical: 4,
        paddingHorizontal: 10,
        marginBottom: 8,
    },
    badgeUnassigned: { backgroundColor: colors.orangeBg },
    badgeUnassignedText: { color: colors.orange, fontSize: 11, fontWeight: "700" },
    badgeClosed: { backgroundColor: "#e5e7eb" },
    badgeClosedText: { color: "#374151", fontSize: 11, fontWeight: "700" },
    badgeRecurring: { backgroundColor: "#f5f3ff" },
    badgeRecurringText: { color: "#7c3aed", fontSize: 11, fontWeight: "700" },
    jobNumber: {
        fontSize: 11,
        fontWeight: "700",
        color: colors.blue,
        marginBottom: 6,
        textTransform: "uppercase",
    },
    jobTitle: { fontSize: 15, fontWeight: "700", color: colors.text, marginBottom: 6 },
    jobDesc: { fontSize: 13, color: colors.subtext, marginBottom: 10, lineHeight: 18 },
    jobInfoRow: {
        borderTopWidth: 1,
        borderTopColor: "#f1f5f9",
        paddingTop: 8,
        gap: 3,
    },
    jobInfoText: { fontSize: 11, color: colors.subtext },
    jobFooterRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 10,
    },
    priorityPill: {
        backgroundColor: "#f1f5f9",
        color: "#475569",
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        fontSize: 10,
        fontWeight: "600",
        overflow: "hidden",
        textTransform: "capitalize",
    },
    scheduleRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 10,
        backgroundColor: "#f8fafc",
        borderRadius: 10,
        padding: 10,
    },
    scheduleLabel: { fontSize: 10, color: colors.muted },
    scheduleValue: { fontSize: 12, fontWeight: "700", color: "#334155", marginTop: 2 },

    actionBtn: {
        marginTop: 12,
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: "center",
    },
    actionBtnTake: { backgroundColor: colors.blue },
    actionBtnInvoice: { backgroundColor: colors.green },
    actionBtnText: { color: "#fff", fontWeight: "700", fontSize: 13 },
    openHint: {
        marginTop: 8,
        fontSize: 11,
        color: colors.muted,
        textAlign: "center",
    },

    emptyBox: {
        borderWidth: 2,
        borderColor: "#cbd5e1",
        borderStyle: "dashed",
        borderRadius: 12,
        paddingVertical: 40,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyText: { color: colors.muted, fontSize: 13 },

    /* ===================== INVOICES TABLE ===================== */
    invoiceRow: {
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        padding: 14,
        marginBottom: 10,
    },
    invoiceNumber: { fontWeight: "700", color: colors.text, fontSize: 14, marginBottom: 4 },
    invoiceMeta: { fontSize: 12, color: colors.subtext, marginBottom: 2 },
    invoiceStatusPill: {
        alignSelf: "flex-start",
        backgroundColor: "#dcfce7",
        borderRadius: 999,
        paddingVertical: 3,
        paddingHorizontal: 10,
        marginTop: 6,
    },
    invoiceStatusText: {
        color: "#166534",
        fontSize: 11,
        fontWeight: "700",
        textTransform: "capitalize",
    },
    invoiceTotal: { fontWeight: "800", fontSize: 15, color: colors.text, marginTop: 6 },

    /* ===================== MODAL ===================== */
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15,23,42,0.62)",
        justifyContent: "flex-end",
    },
    modalCard: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: "92%",
        minHeight: "60%",
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 18,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#e5e7eb",
    },
    modalHeaderLabel: {
        fontSize: 11,
        fontWeight: "700",
        color: colors.subtext,
        textTransform: "uppercase",
        marginBottom: 4,
    },
    modalHeaderTitle: { fontSize: 19, fontWeight: "800", color: "#0f172a" },
    modalHeaderSub: { fontSize: 13, color: colors.subtext, marginTop: 2 },
    modalCloseBtn: {
        width: 38,
        height: 38,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border2,
        backgroundColor: "#f8fafc",
        alignItems: "center",
        justifyContent: "center",
    },
    modalCloseText: { fontSize: 20, color: "#475569" },
    modalBody: {
        paddingHorizontal: 18,
        paddingVertical: 16,
        backgroundColor: "#f8fafc",
    },
    modalFooter: {
        flexDirection: "row",
        gap: 10,
        paddingHorizontal: 18,
        paddingVertical: 14,
        borderTopWidth: 1,
        borderTopColor: "#e5e7eb",
        backgroundColor: "#fff",
    },

    /* ===================== POPUP SECTIONS ===================== */
    section: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: colors.border2,
        borderRadius: 14,
        padding: 16,
        marginBottom: 14,
    },
    sectionHeadTitle: { fontSize: 15, fontWeight: "800", color: "#0f172a" },
    sectionHeadSub: { fontSize: 12, color: colors.subtext, marginTop: 3 },

    fieldWrap: { marginBottom: 12 },
    fieldLabel: { fontSize: 12, fontWeight: "700", color: "#334155", marginBottom: 6 },
    input: {
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 10,
        height: 44,
        paddingHorizontal: 12,
        fontSize: 14,
        color: "#0f172a",
        backgroundColor: "#fff",
    },
    textarea: {
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 10,
        minHeight: 90,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: "#0f172a",
        backgroundColor: "#fff",
        textAlignVertical: "top",
    },

    chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    chip: {
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 999,
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: "#fff",
    },
    chipActive: { backgroundColor: colors.blue, borderColor: colors.blue },
    chipText: { fontSize: 12, fontWeight: "600", color: "#334155" },
    chipTextActive: { color: "#fff" },

    infoGridSmall: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 10 },
    infoBoxSmall: {
        backgroundColor: "#f8fafc",
        borderWidth: 1,
        borderColor: colors.border2,
        borderRadius: 10,
        padding: 12,
        minWidth: "45%",
        flexGrow: 1,
    },

    multiSelectList: { gap: 8, maxHeight: 260 },
    multiSelectItem: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
        padding: 12,
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: colors.border2,
        borderRadius: 11,
    },
    multiSelectItemSelected: {
        borderColor: "#3b82f6",
        backgroundColor: "#eff6ff",
    },
    checkbox: {
        width: 18,
        height: 18,
        borderRadius: 4,
        borderWidth: 1.5,
        borderColor: "#94a3b8",
        alignItems: "center",
        justifyContent: "center",
    },
    checkboxChecked: { backgroundColor: colors.blue, borderColor: colors.blue },
    checkboxMark: { color: "#fff", fontSize: 12, fontWeight: "700" },

    chipList: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
    itemChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: colors.blueBg,
        borderWidth: 1,
        borderColor: colors.blueBorder,
        borderRadius: 999,
        paddingVertical: 6,
        paddingHorizontal: 10,
    },
    itemChipText: { color: "#1d4ed8", fontSize: 12, fontWeight: "700" },

    partCard: {
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: colors.border2,
        borderRadius: 12,
        padding: 14,
        marginTop: 10,
    },
    partMetaText: { fontSize: 11, color: colors.subtext },

    /* ===================== BUTTONS ===================== */
    btnPrimary: {
        backgroundColor: colors.blue,
        borderRadius: 9,
        paddingVertical: 11,
        alignItems: "center",
        flex: 1,
    },
    btnPrimaryText: { color: "#fff", fontWeight: "700", fontSize: 13 },
    btnSecondary: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 9,
        paddingVertical: 11,
        alignItems: "center",
        flex: 1,
    },
    btnSecondaryText: { color: "#334155", fontWeight: "700", fontSize: 13 },
    btnGreen: {
        backgroundColor: colors.green,
        borderRadius: 9,
        paddingVertical: 11,
        alignItems: "center",
        flex: 1,
    },
    btnGreenText: { color: "#fff", fontWeight: "700", fontSize: 13 },
    btnDisabled: { opacity: 0.55 },

    row: { flexDirection: "row", gap: 10 },
    rowWrap: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    flexHalf: { flex: 1, minWidth: "45%" },
});